spring:
application:
  name: turbine

server:
  port: 8087

eureka:
instance:
    leaseRenewalIntervalInSeconds: 10
client:
    serviceUrl:
      defaultZone: ${KUBERNETES_SERVICE:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

turbine:
  clusterNameExpression: new String("default")
  appConfig: HYSTRIX-EXAMPLE-SERVICE,HYSTRIX-EXAMPLE-SERVICE2,CUSTOMER-CLIENT-SERVICE
  combineHostPort: true



  #8082