server:
  port: 9090


spring:
  application:
    name: zuul-server



zuul:
  #ignoredServices: "*"
  routes:
    customer-service:
      path: /customer-service/**
      serviceId: customer-service

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka/

