eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${KUBERNETES_SERVICE:http://localhost:8761}/eureka/

management.security.enabled: false