apiVersion: v1
kind: Pod
metadata:
  name: discovery
  labels:
    name: discovery
spec:
  containers:
  - name: discovery
    image: "miguelrapolli69/eukica-machine"
    imagePullPolicy: Always
    ports:
      - containerPort: 8761
---

apiVersion: v1
kind: Service
metadata:
  name: discovery
spec:
  type: NodePort
  selector:
    name: discovery
  ports:
    - port: 8761
      nodePort: 31852
---

apiVersion: v1
kind: Service
metadata:
  name: edge
spec:
  type: NodePort
  selector:
    name: edge
  ports:
    - port: 9090
      nodePort: 31853


---


apiVersion: v1
kind: Pod
metadata:
  name: edge
spec:
  containers:
  - name: edge
    image: "miguelrapolli69/zuul-machine"
    imagePullPolicy: Always
    ports:
        - containerPort: 9090

---

apiVersion: v1
kind: Pod
metadata:
  name: monitor
spec:
  containers:
  - name: monitor
    image: "miguelrapolli69/hystrix-machine"
    ports:
        - containerPort: 8089

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: order
  labels:
    name: order
spec:
  replicas: 1
  selector:
    name: order
  template:
    metadata:
      labels:
        name: order
    spec:
      containers:
      - name: order
        image: "miguelrapolli69/service-machine"
        ports:
          - containerPort: 9098

---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  selector:
    name: order
  ports:
    - port: 9098

